# Generated by Django 5.1.7 on 2025-03-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_amenities_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_occupancy_per_room',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='occupants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms_reserved',
            field=models.IntegerField(default=1),
        ),
    ]
